"""initial schema

Revision ID: bb1541dd8090
Revises: 
Create Date: 2026-04-14 16:36:20.441069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1541dd8090'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sic_code', sa.String(), nullable=True),
    sa.Column('sic_description', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_filing_at', sa.Date(), nullable=True),
    sa.Column('last_filing_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.Text(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.SmallInteger(), nullable=True),
    sa.Column('raw_s3_key', sa.Text(), nullable=False),
    sa.Column('raw_size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_extracted', sa.Boolean(), nullable=False),
    sa.Column('is_xbrl_parsed', sa.Boolean(), nullable=False),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('is_signal_scored', sa.Boolean(), nullable=False),
    sa.Column('is_anomaly_scored', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_table('filing_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('sequence_idx', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', 'section', 'sequence_idx', name='uq_filing_sections_filing_section_seq')
    )
    op.create_table('guidance_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('guided_point', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('guidance_period_end', sa.Date(), nullable=True),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insider_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('insider_name', sa.Text(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('shares', sa.Numeric(), nullable=False),
    sa.Column('price_per_share', sa.Numeric(), nullable=True),
    sa.Column('total_value', sa.Numeric(), nullable=True),
    sa.Column('is_derivative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'insider_name', 'transaction_date', 'transaction_code', 'shares', 'price_per_share', name='uq_insider_transaction_dedup')
    )
    op.create_table('pipeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('pipeline_layer', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rlds', sa.Float(), nullable=True),
    sa.Column('gce', sa.Float(), nullable=True),
    sa.Column('ita', sa.Float(), nullable=True),
    sa.Column('convergence', sa.Boolean(), nullable=False),
    sa.Column('convergence_reason', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id', name='uq_signal_scores_filing_id')
    )
    op.create_table('xbrl_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('taxonomy', sa.String(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('decimals', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.SmallInteger(), nullable=True),
    sa.Column('form_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'taxonomy', 'concept', 'period_end', 'unit', name='uq_xbrl_fact_business_key')
    )
    op.create_table('nci_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('signal_score_id', sa.Integer(), nullable=True),
    sa.Column('nci_global', sa.Float(), nullable=False),
    sa.Column('nci_lower', sa.Float(), nullable=True),
    sa.Column('nci_upper', sa.Float(), nullable=True),
    sa.Column('data_fresh', sa.Boolean(), nullable=False),
    sa.Column('staleness_reason', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('top_anomalous_paragraphs', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_score_id'], ['signal_scores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'computed_at', name='uq_nci_company_computed_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nci_scores')
    op.drop_table('xbrl_facts')
    op.drop_table('signal_scores')
    op.drop_table('pipeline_events')
    op.drop_table('insider_transactions')
    op.drop_table('guidance_statements')
    op.drop_table('filing_sections')
    op.drop_table('filings')
    op.drop_table('companies')
    # ### end Alembic commands ###
