"""add layer to pipeline_events

Revision ID: 425d135dbfab
Revises: bb1541dd8090
Create Date: 2026-04-15 07:31:56.777240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '425d135dbfab'
down_revision: Union[str, None] = 'bb1541dd8090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_events', sa.Column('layer', sa.Text(), nullable=False))
    op.add_column('pipeline_events', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('pipeline_events', sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pipeline_events', sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('pipeline_events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pipeline_events', 'event_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('pipeline_events', 'pipeline_layer')
    op.drop_column('pipeline_events', 'created_at')
    op.drop_column('pipeline_events', 'error_message')
    op.drop_column('pipeline_events', 'details')
    op.drop_column('pipeline_events', 'event_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_events', sa.Column('event_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('pipeline_events', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('pipeline_events', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pipeline_events', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('pipeline_events', sa.Column('pipeline_layer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('pipeline_events', 'event_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('pipeline_events', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('pipeline_events', 'occurred_at')
    op.drop_column('pipeline_events', 'detail')
    op.drop_column('pipeline_events', 'duration_ms')
    op.drop_column('pipeline_events', 'layer')
    # ### end Alembic commands ###
